### PR TITLE
Fixes: shutter id case & webui word wrapping

### PR DESCRIPTION
**Pull request by malys**
Hi Nick,
Thx you for your project.
I have detected some problems:
* the case of shutterid is not consistent: I force it to upper case(HIGH)
* shutter name in webui is not wrapped (LOW). I have applied a quick fix in css to wrap it
Be free to integrate or inspire you from my code.

Bye

### CODE REVIEW

**Comment by malys** [comment]
Thanks to this fixes.
Pi-somfy is very stable at home.
It's very necessary to not use le same RTS_ADDRESS to reconfigure your shutters. @Nickduino

**Comment by Nickduino** [comment]
> It's mandatory to not use le same RTS_ADDRESS to reconfigure your shutters. 

Why would you need to reconfigure your shutters?

**Comment by malys** [comment]
Hi @Nickduino ,

I have a daily backup but I dont't know the trick to "add 10 ... ".
I will apply this strategy next time.
Analysing code, I understood that rolling code is only an incrememental of initial code (bu shutterid) every time that you use  it?
It could interesting to add your last comment in redme file?

Thanks for your advice and your project.

**Comment by Nickduino** [comment]
> Analysing code, I understood that rolling code is only an incrememental of initial code

Yes, Somfy made things pretty simple.
In your conf file, you see a number in front of every remote address: that's your rolling code. You can't reuse the same code twice.

So if you have a power cut that empties your config while the rolling code was 347 and you restore your backup of the morning that was at 342 as is, your shutters won't move. Increment 342 of a few units to **at least** 347 and it will work. Of course you don't know it was 347 when it failed, that's why I suggested to increase it by 10. If you use your shutters a lot, you might want to pick a higher number; there is a higher limit but I don't remember it.

Alternatively, you could restore your config file and press the buttons on the GUI : at some point, the rolling code of the remote will catch the rolling code stored in the shutter.

**Pull request closed without merging**
