### PR TITLE
Preset position

### PR DESCRIPTION
**Pull request by nungesser**
Hi,
I've added a [ShutterPresets] entrie in the config to make the position prediction more accurate.

Likewise, I modified waitAndSetFinalPosition() to make it rely on state.lastCommandTime instead of state.position.
Assume the shutter is in the preset position, if you press up (or down), then press stop twice right after. It will go back to the initial preset position. The waitAndSetFinalPosition() relying on position would fire and modify the position value inappropriately.

Rémi

### CODE REVIEW

**Comment by rbswift** [comment]
I really welcome the waitAndSetFinalPosition change. Thank you. I'd been looking at something similar because the current implementation breaks in some scenarios where commands are issued in reasonably quick succession.

Somfy call what you have named the "preset" position either the "my" position or the "intermediate" position so if you wanted to use either term it would be a bit more consistent.

**Comment by nungesser** [comment]
Ok, my equipment is from Simu brand (at least the original remote). It behaves exactly the same. The manual does not mention "my" position but it describes it as "intermediate" position.
Shall I go for [ShutterIntermediates] ?

**Comment by rbswift** [comment]
[ShutterIntermediatePositions] might make it a bit more obvious

**Comment by rbswift** [comment]
Also maybe consider that it is possible that some motors will not have an intermediate position saved (either in the motor or the config file) so maybe need to do a check first to see if there is actually an intermediate position configured. If there is not then the motor will not move.

**Comment by nungesser** [comment]
When I reseted my motors, they had a default intermediate position which is about 15%. Shutter still closed but it leaves ray lights coming in.
I believe there is no way to clear the intermediate position in my case.
Don't you have this behavior ?

**Comment by rbswift** [comment]
See page 18 ... https://www.somfypro.com.au/documents/40597799/0/SOM6590+Pocket+Book+Installers+Guide+2014_LR2+%282%29.pdf/

Press the stop button in the intermediate position for 5 seconds to delete the intermediate position.

**Comment by nungesser** [comment]
That's right, thanks. I'll add this

**Comment by Nickduino** [comment]
> Ok, my equipment is from Simu brand

Ahah, moi aussi !

**Comment by MichaelB2018** [comment]
quick question. It looks like it's backward compatible (ie people don't have a [ShutterIntermediatePositions] in their own config file. Is that correct? If that's tested I'll merge.

**Comment by nungesser** [comment]
That's correct, it will work.
In that case, default behavior will be to keep the position value when stop button pressed while stationary (No intermediate position stored).
In the current implementation, it's set arbitrarily to 50.

**Comment by MichaelB2018** [comment]
Merged. Thanks for the change!

**Comment by nungesser** [comment]
Thank you guys ! This project helps a lot.
Glad to contribute

**Pull request merged**
