### PR TITLE
Fixed issue #39

### PR DESCRIPTION
**Pull request by FraBoCH**
Fixed issue #39

### CODE REVIEW

**Comment by rbswift** [comment]
seems to work well for me - thanks!

**Comment by FraBoCH** [comment]
> seems to work well for me - thanks!

Thanks for the feedback, I still prefer to wait for @Nickduino or @MichaelB2018 review before merging to master

**Comment by Nickduino** [comment]
I'm away, can't test it before next week.

If you're reasonably confident it's working, I'm fine with a merge

**Comment by MichaelB2018** [comment]
Checked it and works well, Thanks!

**Comment by ToddGreenfield** [comment]
Thanks all! Works great now.

**Pull request merged**
